name: Sync fork with upstream
on:
  schedule:
    - cron: '0 0 * * 1' # scheduled for 00:00 every Monday
  workflow_dispatch: # Allow manual triggering via Web UI to test.

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: dev
          # Recent GitHub changes needs a token with `workflow` permissions, so
          # the default GITHUB_TOKEN does not work anymore
          token: ${{ secrets.PAT_TOKEN }}